// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  x: __t.i32(),
  y: __t.i32(),
  spawnTick: __t.u64().name("spawn_tick"),
  expireTick: __t.u64().name("expire_tick"),
  ownerPlayerId: __t.string().name("owner_player_id"),
  state: __t.string(),
  isConnected: __t.bool().name("is_connected"),
  output: __t.i32(),
  effectiveOutput: __t.i32().name("effective_output"),
  lastNetworkSolveTick: __t.u64().name("last_network_solve_tick"),
});
