// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  ownerPlayerId: __t.string().name("owner_player_id"),
  aGeneratorId: __t.string().name("a_generator_id"),
  bGeneratorId: __t.string().name("b_generator_id"),
  length: __t.i32(),
  capacity: __t.i32(),
  load: __t.i32(),
  temp: __t.i32(),
  overheated: __t.bool(),
  active: __t.bool(),
  cooldownUntilTick: __t.u64().name("cooldown_until_tick"),
  createdAtTick: __t.u64().name("created_at_tick"),
});
