// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  tick: __t.u64(),
  playerId: __t.string().name("player_id"),
  seq: __t.u64(),
  actionType: __t.string().name("action_type"),
  payloadJson: __t.string().name("payload_json"),
  dx: __t.i32(),
  dy: __t.i32(),
});
