// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.string().primaryKey().name("player_id"),
  posX: __t.i64().name("pos_x"),
  posY: __t.i64().name("pos_y"),
  targetPosX: __t.i64().name("target_pos_x"),
  targetPosY: __t.i64().name("target_pos_y"),
  moving: __t.bool(),
  speedFixedPerTick: __t.i64().name("speed_fixed_per_tick"),
  lastProcessedTick: __t.u64().name("last_processed_tick"),
  lastUpdatedTick: __t.u64().name("last_updated_tick"),
  rootGeneratorId: __t.string().name("root_generator_id"),
  rootMoveAvailableAtTick: __t.u64().name("root_move_available_at_tick"),
  networkDirty: __t.bool().name("network_dirty"),
});
