// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Generator = __t.object("Generator", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  spawnTick: __t.u64(),
  expireTick: __t.u64(),
  ownerPlayerId: __t.string(),
  state: __t.string(),
});
export type Generator = __Infer<typeof Generator>;

export const Obstacle = __t.object("Obstacle", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
});
export type Obstacle = __Infer<typeof Obstacle>;

export const PendingAction = __t.object("PendingAction", {
  id: __t.string(),
  tick: __t.u64(),
  playerId: __t.string(),
  seq: __t.u64(),
  actionType: __t.string(),
  payloadJson: __t.string(),
  dx: __t.i32(),
  dy: __t.i32(),
});
export type PendingAction = __Infer<typeof PendingAction>;

export const Player = __t.object("Player", {
  playerId: __t.string(),
  posX: __t.i64(),
  posY: __t.i64(),
  lastProcessedTick: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerSession = __t.object("PlayerSession", {
  playerId: __t.string(),
  lastSeq: __t.u64(),
  actionBudget: __t.u16(),
  lastBudgetTick: __t.u64(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const SpawnMarker = __t.object("SpawnMarker", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  spawnTick: __t.u64(),
});
export type SpawnMarker = __Infer<typeof SpawnMarker>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const WorldConfig = __t.object("WorldConfig", {
  id: __t.string(),
  ticksPerDay: __t.u32(),
  waveEveryDays: __t.u32(),
  markerLeadDays: __t.u32(),
  generatorLifeDays: __t.u32(),
  waveSize: __t.u32(),
});
export type WorldConfig = __Infer<typeof WorldConfig>;

export const WorldState = __t.object("WorldState", {
  id: __t.string(),
  currentTick: __t.u64(),
  tickRate: __t.u16(),
  seed: __t.u32(),
});
export type WorldState = __Infer<typeof WorldState>;

