// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const CaptureAttempt = __t.object("CaptureAttempt", {
  generatorId: __t.string(),
  playerId: __t.string(),
  startTick: __t.u64(),
  finishTick: __t.u64(),
});
export type CaptureAttempt = __Infer<typeof CaptureAttempt>;

export const EventLog = __t.object("EventLog", {
  id: __t.string(),
  tick: __t.u64(),
  eventType: __t.string(),
  payloadJson: __t.string(),
});
export type EventLog = __Infer<typeof EventLog>;

export const Generator = __t.object("Generator", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  spawnTick: __t.u64(),
  expireTick: __t.u64(),
  ownerPlayerId: __t.string(),
  state: __t.string(),
  reservedByPlayerId: __t.string(),
  isConnected: __t.bool(),
  output: __t.i32(),
  effectiveOutput: __t.i32(),
  lastNetworkSolveTick: __t.u64(),
});
export type Generator = __Infer<typeof Generator>;

export const Junk = __t.object("Junk", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  kind: __t.i32(),
});
export type Junk = __Infer<typeof Junk>;

export const Line = __t.object("Line", {
  id: __t.string(),
  ownerPlayerId: __t.string(),
  aGeneratorId: __t.string(),
  bGeneratorId: __t.string(),
  aX: __t.i32(),
  aY: __t.i32(),
  bX: __t.i32(),
  bY: __t.i32(),
  length: __t.i32(),
  capacity: __t.i32(),
  load: __t.i32(),
  temp: __t.i32(),
  overheated: __t.bool(),
  active: __t.bool(),
  cooldownUntilTick: __t.u64(),
  createdAtTick: __t.u64(),
});
export type Line = __Infer<typeof Line>;

export const Obstacle = __t.object("Obstacle", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
});
export type Obstacle = __Infer<typeof Obstacle>;

export const PendingAction = __t.object("PendingAction", {
  id: __t.string(),
  tick: __t.u64(),
  playerId: __t.string(),
  seq: __t.u64(),
  actionType: __t.string(),
  payloadJson: __t.string(),
  dx: __t.i32(),
  dy: __t.i32(),
});
export type PendingAction = __Infer<typeof PendingAction>;

export const Player = __t.object("Player", {
  playerId: __t.string(),
  posX: __t.i64(),
  posY: __t.i64(),
  targetPosX: __t.i64(),
  targetPosY: __t.i64(),
  moving: __t.bool(),
  speedFixedPerTick: __t.i64(),
  lastProcessedTick: __t.u64(),
  lastUpdatedTick: __t.u64(),
  rootGeneratorId: __t.string(),
  rootMoveAvailableAtTick: __t.u64(),
  networkDirty: __t.bool(),
});
export type Player = __Infer<typeof Player>;

export const PlayerSession = __t.object("PlayerSession", {
  playerId: __t.string(),
  lastSeq: __t.u64(),
  actionBudget: __t.u16(),
  lastBudgetTick: __t.u64(),
});
export type PlayerSession = __Infer<typeof PlayerSession>;

export const RootNode = __t.object("RootNode", {
  playerId: __t.string(),
  generatorId: __t.string(),
  placedAtTick: __t.u64(),
});
export type RootNode = __Infer<typeof RootNode>;

export const RootRelocation = __t.object("RootRelocation", {
  playerId: __t.string(),
  fromGeneratorId: __t.string(),
  toGeneratorId: __t.string(),
  startTick: __t.u64(),
  finishTick: __t.u64(),
});
export type RootRelocation = __Infer<typeof RootRelocation>;

export const SpawnMarker = __t.object("SpawnMarker", {
  id: __t.string(),
  x: __t.i32(),
  y: __t.i32(),
  spawnTick: __t.u64(),
});
export type SpawnMarker = __Infer<typeof SpawnMarker>;

export const TickSchedule = __t.object("TickSchedule", {
  scheduledId: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type TickSchedule = __Infer<typeof TickSchedule>;

export const WorldConfig = __t.object("WorldConfig", {
  id: __t.string(),
  ticksPerDay: __t.u32(),
  ticksPerMinute: __t.u32(),
  waveEveryDays: __t.u32(),
  markerLeadDays: __t.u32(),
  generatorLifeDays: __t.u32(),
  waveSize: __t.u32(),
  worldWidth: __t.u32(),
  worldHeight: __t.u32(),
  tileSizePx: __t.u16(),
  interactRangeCells: __t.u32(),
  captureDurationTicks: __t.u64(),
  enableTestAdmin: __t.bool(),
});
export type WorldConfig = __Infer<typeof WorldConfig>;

export const WorldState = __t.object("WorldState", {
  id: __t.string(),
  currentTick: __t.u64(),
  tickRate: __t.u16(),
  seed: __t.u32(),
});
export type WorldState = __Infer<typeof WorldState>;

