// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default {
  ticksPerDay: __t.u32(),
  ticksPerMinute: __t.u32(),
  waveEveryDays: __t.u32(),
  markerLeadDays: __t.u32(),
  generatorLifeDays: __t.u32(),
  waveSize: __t.u32(),
};
