// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.string().primaryKey(),
  ticksPerDay: __t.u32().name("ticks_per_day"),
  waveEveryDays: __t.u32().name("wave_every_days"),
  markerLeadDays: __t.u32().name("marker_lead_days"),
  generatorLifeDays: __t.u32().name("generator_life_days"),
  waveSize: __t.u32().name("wave_size"),
});
