// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import ApplyMoveReducer from "../apply_move_reducer";
import EnqueueActionReducer from "../enqueue_action_reducer";
import JoinPlayerReducer from "../join_player_reducer";

export type ApplyMoveParams = __Infer<typeof ApplyMoveReducer>;
export type EnqueueActionParams = __Infer<typeof EnqueueActionReducer>;
export type JoinPlayerParams = __Infer<typeof JoinPlayerReducer>;

